apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jewhmj61n-python 
  janus-idp.io/tekton: jewhmj61n-python
  backstage.io/kubernetes-id: jewhmj61n-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jewhmj61n-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml